name: test
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run go unit tests
        run: go test
      
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Check Go Code is Formatted
        run: |-
          unformatedFiles=$(gofmt -l ./)
          [ -z "$unformatedFiles" ] && exit 0
          echo >&2 "The following files are not formatted:"
          echo "$unformatedFiles"
          echo >&2 "Run 'go fmt ./...' to format the files."
          exit 1
      - name: Run go vet
        run: go vet ./...

  all-tests-passed:
    name: All tests passed
    runs-on: ubuntu-latest
    needs: [tests, code-quality]
    if: always()
    steps:
      - name: Check tests/code-quality job status
        run: |
          if [ "${{ needs.tests.result }}" != "success" ] || [ "${{ needs.code-quality.result }}" != "success" ]; then
            echo "tests or code-quality job did not succeed"
            exit 1
          fi