name: test
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Run go unit tests
        run: go test
      
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Check Go Code is Formatted
        run: |-
          unformatedFiles=$(gofmt -l ./)
          [ -z "$unformatedFiles" ] && exit 0
          echo >&2 "The following files are not formatted:"
          echo "$unformatedFiles"
          echo >&2 "Run 'go fmt ./...' to format the files."
          exit 1
      - name: Run go vet
        run: go vet ./...